### ISSUE TITLE
No section: 'root_url'

### ISSUE THREAD

**Issue by bbmusa** [symphonyfintech/xts-pythonclient-api-sdk#7]
How do i fix this ?

```
Traceback (most recent call last):
  File "/app/main/lambda_function.py", line 8, in <module>
    from Connect import XTSConnect
  File "/app/main/Connect.py", line 33, in <module>
    class XTSConnect(XTSCommon):
  File "/app/main/Connect.py", line 44, in XTSConnect
    _default_root_uri = cfg.get('root_url', 'root')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'root_url'
```

**Comment by NawazSid** [comment]
Hi, 
See if there's a [rool_url] section in the "config.ini" file

**Comment by SHIVANIUM-GIT** [comment]
> Hi, See if there's a [rool_url] section in the "config.ini" file

yes, present
